version: "3.8"
services:
  app:
    image: valeron12345/flask_app:2.0.0
    links:
      - mysql
    ports:
      - "5000:5000"
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - mysql
        
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - /var/run/mysqlDocker/init:/docker-entrypoint-initdb.d
      - /var/run/mysqlDocker/var:/var/lib/mysql

networks:
  default:
    external: false
    name: app_network
